version: '3.3'
services:
  nginx:
    build: ./nginx
    ports:
      - '80:80'
      - '443:443'
  mongo:
    image:  mongo:6.0.4
    ports:
      - '27017:27017'
  myapp:
    build:  .
    environment:
      WAIT_HOSTS: mongo:27017
    ports:
      - '8080:8080'